### ISSUE TITLE
所有仓库已删除,请找此人维护

### ISSUE THREAD

**Issue by guanggaobixusi** [jqyisbest/RuCu6#1]
所有仓库已删除,请找此人维护

**Comment by jqyisbest** [comment]
只是fork就已经被那畜生挂在频道里污蔑为剽窃，还要大伙人肉我。我还敢维护？

![SBRUCU64000+](https://github.com/user-attachments/assets/26e3390f-af84-4093-85f5-67edb55e170c)

代码就在这里，Loon也还挺方便调试，没混淆的代码有问题可以自己改，混淆的代码你就算跪求它它也没本事给你改。

**Comment by jqyisbest** [comment]
挺好笑的。自己fork别人代码不提pr、偷别人代码还要骂别人，转头要求大家不能fork自己偷来的代码，谁fork就拉黑羞辱挂频道三件套，还拿删库跑路威胁大家不准fork哈哈哈。又蠢又坏，社会的渣滓。
